# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Prod environment
variables:
  # Global
  ap_vm_image: ubuntu-20.04

  namespace: rizo13 #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: 002
  location: canadacentral
  environment: prod
  enable_aml_computecluster: true
  enable_monitoring: false
  # feature store details
  enable_feature_store: true
  sql_admin_user: sqladmin
  sql_admin_password: ThisIsNotVerySecure!
  fs_onlinestore_conn_name: FEATHR-ONLINE-STORE-CONN
  feathr_app_image: feathrfeaturestore/feathr-registry
  feathr_app_image_tag: releases-v0.9.0
  react_enable_rbac: true
  aad_client_id: 2327c20b-fa88-46eb-8a3a-57283a716619 # refer to prefeaturestore readme for details
  spark_version: 3.1
  priviledged_object_id: 7cbdebc0-e724-4683-9094-4c0cb8a4266f # AAD Object ID for user, used to set pividges for user in KV and Synapse for feature store components
  # added flag for this:  https://registry.terraform.io/providers/hashicorp/azurerm/2.99.0/docs/guides/3.0-app-service-beta
  # remove the environment variable when this is no longer required
  ARM_THREEPOINTZERO_BETA_RESOURCES: true

  # data storage settings
  data_container_name: nyctaxi
  adls_scheme: https
  adls_data_directory: feathr_demo_data
  adls_data_file: feathr_data.csv

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Prod
  ado_service_connection_aml_ws: Azure-ARM-Prod

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: rg-$(namespace)-$(postfix)$(environment)
  aml_workspace: mlw-$(namespace)-$(postfix)$(environment)
  application_insights: mlw-$(namespace)-$(postfix)$(environment)
  key_vault: kv-$(namespace)-$(postfix)$(environment)
  container_registry: cr$(namespace)$(postfix)$(environment)
  storage_account: st$(namespace)$(postfix)$(environment)

  # For terraform reference
  terraform_version: 1.3.6
  terraform_workingdir: infrastructure
  terraform_st_location: $(location)
  terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf
  terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  terraform_st_container_name: default
  terraform_st_key: mlops-tab

  # For feathr reference
  resource_prefix: $(namespace)fs
  key_vault_name: kv-$(resource_prefix)-$(postfix)$(environment)
  synapse_workspace_name: sy$(resource_prefix)-$(postfix)$(environment)
  adls_account: st$(resource_prefix)$(postfix)$(environment)
  adls_fs_name: dl$(resource_prefix)$(postfix)$(environment)
  redis_name: rd$(resource_prefix)$(postfix)$(environment)
  webapp_name: app$(resource_prefix)$(postfix)$(environment)
  # sp_name: sp$(resource_prefix)$(postfix)$(environment)
