# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      # 'main' branch: PRD environment
      - template: ../../config-infra-dev.yml
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      # 'develop' or feature branches: DEV environment
      - template: ../../config-infra-dev.yml
  - name: version
    value: aml-cli-v2
  # - group: env-variables

trigger:
  - main

pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
    - repository: mlops-templates # Template Repo
      name: Azure/mlops-templates # need to change org name from "Azure" to your own org
      endpoint: Rizo-R # need to set up and hardcode
      type: github
      ref: feature/feathr

      

stages:
  - stage: DeployTrainingPipeline
    displayName: Deploy Training Pipeline
    jobs:
      - job: DeployTrainingPipeline
        timeoutInMinutes: 120 # how long to run the job before automatically cancelling
        steps:
          - checkout: self
            path: s/
          - checkout: mlops-templates
            path: s/templates/
          - template: templates/${{ variables.version }}/install-az-cli.yml@mlops-templates
          - template: templates/${{ variables.version }}/install-aml-cli.yml@mlops-templates
          - template: templates/${{ variables.version }}/connect-to-workspace.yml@mlops-templates
          - template: templates/${{ variables.version }}/register-environment.yml@mlops-templates
            parameters:
              environment_name: feathr-demo-env
              environment_file: mlops/azureml/train/train-env.yml
          - template: templates/${{ variables.version }}/create-compute.yml@mlops-templates
            parameters:
              cluster_name: cpu-cluster
              size: Standard_DS3_v2
              min_instances: 0
              max_instances: 4
              cluster_tier: low_priority
          - template: templates/${{ variables.version }}/register-data.yml@mlops-templates
            parameters:
              data_type: uri_file
              data_name: feathr-data
              data_file: mlops/azureml/train/data.yml
          # - template: templates/${{ variables.version }}/create-service-principal.yml@mlops-templates
          #   parameters:
          #     sp_name: $(sp_name)
          - template: templates/${{ variables.version }}/run-pipeline.yml@mlops-templates
            parameters:
              pipeline_file: mlops/azureml/train/pipeline.yml
              experiment_name: $(environment)_taxi_fare_train_$(Build.SourceBranchName)
              display_name: $(environment)_taxi_fare_run_$(Build.BuildID)
              enable_monitoring: $(enable_monitoring)
              key_vault_name: $(key_vault_name)
              synapse_workspace_name: $(synapse_workspace_name)
              adls_account: $(adls_account)
              adls_fs_name: $(adls_fs_name)
              redis_name: $(redis_name)
              webapp_name: $(webapp_name)
              # sp_client_id: $(service_principal_id)
              # sp_client_secret: $(service_principal_secret)
              # tenant_id: $(tenant_id)